**Dr. Fatma Ibahim**

**TU Dortmund**

# Numpy 

The NumPy (stands for 'Numerical Python')
package provides basic routines for manipulating large arrays and matrices of numeric data.

## Importing the NumPy module

In [2]:
import numpy as np


## Creating NumPy Array


### 1.From a List

 Pass a Python list to the 'array' function to create a Numpy array
#### a. Single-dimensional Numpy Array:

In [12]:
# create a Python list 
a_1=
#and pass its variable name to create a Numpy array.
a=
# print they type of a_1 and a
print(type(a_1))
print(type(a))

# you can creat the arry also like this:


<class 'list'>
<class 'numpy.ndarray'>


In [13]:
a

array([1, 4, 5, 8])

#### b.Multi-dimensional Array:


In [3]:
matrix = [[1,2,3],[4,5,6],[7,8,9]] 
s=np.array(matrix)
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### Data type Object (dtype) in NumPy Python :
using  **dtype** function , you can find the type of the items that are stored in an array (e.g. int, float,number of bytes)

In [15]:
#get the type of the data in arrays  s 


dtype('int32')

In [4]:
#Type provided:
a=np.array([1,3,5],dtype=float)

b=np.array([3,2],dtype=complex)
print(a)
print(b)

[1. 3. 5.]
[3.+0.j 2.+0.j]


##### numpy.ndim
 The ndim is the same as the number of axes or the length of the output of x.shape

x=np.array([(1,2,3),(2,4,5)]) 

x.ndim 
is the same as
len(x.shape)

2

(3, 3)

In [19]:
# the same as s.ndim
len(s.shape)

2

#### Size in Numpy

is the total number of elements. 



In [20]:
#get the size of a Matrix  s



9

In [21]:
# check the shape of x-axis and y-axis


(3, 3)

#### slicing



In [3]:
a =np.array([1,2,3,4,5])
for ele in a:
    print(ele)

1
2
3
4
5


In [23]:

a_s[3]

4

In [24]:
a_s[0] = 5

In [25]:
a_s

array([5, 2, 3, 4, 5])

In [14]:
 # all the colum in the first row  
s[:,2]

array([3, 6, 9])

In [28]:
# the second colum



array([3, 6, 9])

In [16]:
# from the last row the last two columns
s[-1,-2:]

array([8, 9])

### 2.Built-in Methods
There are lots of built-in ways to generate Arrays

### arange
Return evenly spaced values within a given interval.

In [30]:

 # to creat array with values ranges from 0 to 9


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# with step size 2


array([0, 2, 4, 6, 8])

In [36]:
# two dimensional arry  using arrange

a_4=
a_4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
# mgrid to creat a matrix
n1,n2=
n1

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [38]:
n2 

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [39]:
# number of row  is 6 and number of columns are 8
n3,n4=np.mgrid[0:6,1:9]
n3

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5]])

In [40]:
n4

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [43]:
#  create a meshgrid by specifying ranges and step lengths using np.arange
n3,n4=
n3

array([[1, 3, 5, 7, 9],
       [1, 3, 5, 7, 9],
       [1, 3, 5, 7, 9],
       [1, 3, 5, 7, 9],
       [1, 3, 5, 7, 9]])

In [10]:
#  linspace:
a1=np.linspace(-5,5,5)

print(a1)


[-5.  -2.5  0.   2.5  5. ]


numpy.ndarray

### Zeros and ones

In [44]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [46]:
# 5by 5 zero matrix
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
np.ones(3)

array([1., 1., 1.])

In [48]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [49]:
np.linspace(0, 10, 3)#  start, end, # elements

array([ 0.,  5., 10.])

In [50]:
# to creat 50 elment between 0 and 10
np.linspace(0,10)


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### eye
Creates an identity matrix

In [31]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## 3.Random
### rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1].

In [51]:

np.random.rand(3)

array([0.72727996, 0.59821675, 0.728348  ])

In [52]:
#  random,rand to create 5 by 5 matrix filled with random values between 0 and 1
np.random.rand(5,5)

array([[0.19868804, 0.89570441, 0.91902712, 0.37593445, 0.15756727],
       [0.76374388, 0.57858542, 0.41764891, 0.60251993, 0.55604545],
       [0.49792136, 0.63927434, 0.20650794, 0.39727603, 0.54429149],
       [0.53092573, 0.84761803, 0.28169953, 0.14953471, 0.7197167 ],
       [0.45947917, 0.41711972, 0.1017613 , 0.50917355, 0.30650091]])

### randn


In [55]:
# creat vector. the values between -inf and inf


array([ 0.79404828, -1.47705438, -0.76342287])

In [56]:

np.random.randn(5, 5)

array([[ 0.44034613, -0.49622735,  1.83321327,  2.41610184, -0.30201041],
       [-2.17169951, -0.88378716,  0.26022364,  0.92709884,  0.78456865],
       [ 0.56512282, -1.29928287, -2.19542985,  1.66093408,  0.74357504],
       [-0.6726351 ,  0.07292477,  0.68308268,  0.45206644,  0.78908195],
       [ 1.03294124, -0.64828562,  0.31833293,  0.70968031, -2.17312151]])

### randint
Return random integers from low (inclusive) to high (exclusive).

In [57]:
#ceart integer random nummber between 1 and 100 and defult number of element is 1


54

In [58]:
# the number of the element is 10 
np.random.randint(0,100,10)


array([88, 35, 76, 79, 74, 39, 57, 70,  1,  5])

## Array Attributes and Methods


In [59]:
arr = np.arange(25)# creat vector
ranarr = np.random.randint(0, 50, 10) # vector avector

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [61]:
ranarr

array([34, 39, 46, 17,  4, 18, 29, 34, 13, 33])

### max,min,argmax,argmin


In [62]:
ranarr

array([34, 39, 46, 17,  4, 18, 29, 34, 13, 33])

In [63]:
ranarr.max()

46

In [64]:
ranarr.min()

4

In [65]:
ranarr.argmax() # to find the location of the max value

2

In [66]:
ranarr.argmin()# location of min value

4

In [67]:
arr = np.array([2, 4, 6, 8])

In [68]:
# to get the summ of the element of arr
arr.sum()

20

In [69]:
# the product 2*4*6*8

arr.prod()

384

In [70]:
# the mean value
arr.mean()


5.0

In [71]:
# variance
arr.var()

5.0

In [72]:
# standard deviation

arr.std()

2.23606797749979

## Python NumPy Array v/s List

the reasons for using Python NumPy instaed of List are :
    
    1- Less Memory
    2-Fast
    3-Convenient

In [73]:
#example  explain the first reason: LESS MEMORY FOR THE NUMPY ARRAY
import time
import sys
L= range(1000)
print(sys.getsizeof(5)*len(L))
 
A= np.arange(1000)
print(A.size*A.itemsize)

28000
4000


In [74]:
# Fast and convenient  : we take in this example the summ of two list and two array and in the end it is clear that the time less
# in the second case.
SIZE = 1000000
L1= range(SIZE)
L2= range(SIZE)
A1= np.arange(SIZE)
A2=np.arange(SIZE)
 
start= time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)
 
start=time.time()
result= A1+A2
print((time.time()-start)*1000)

230.41081428527832
39.893150329589844


Der Nutzerin/dem Nutzer ist bekannt, dass die nachfolgenden Inhalte und Materialien urheberrechtlich geschützt sind. Die Nutzung ist ausschließlich für den persönlichen Gebrauch im Rahmen von universitären Zwecken zulässig. Insbesondere die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung sowie die Weitergabe an Dritte nicht gestattet. Zuwiderhandlungen werden zivil- und strafrechtlich verfolgt.“
